default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5

production:
  <<: *default
  database: backend_production

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test
