version: '3.7'
services:
    db:
        image: postgres:12.3
        volumes:
            - data:/var/lib/postgresql/data
        environment: 
            POSTGRES_HOST_AUTH_METHOD: trust
        networks: 
            - backend
    web:
        build: .
        volumes:
            - .:/backend
        ports:
            - "3000:3000"
        depends_on:
            - db
            - redis
        env_file: .env
        networks: 
            - backend
    dns:    
        build:      
          context: .      
          dockerfile: ./nginx/Dockerfile
        depends_on:      
            - web
        ports:      
            - 80:80
            - 443:443
        networks: 
            - backend
    redis:
        image: 'redis:4.0-alpine'
        command: redis-server
        volumes:
          - 'redis:/data'
        ports:
            - "6379:6379"
        networks: 
            - backend
    
volumes: 
    redis:
    data:
        driver: local
networks: 
    backend:
